default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fizzbuzz_development

test:
  <<: *default
  database: fizzbuzz_test

staging:
  <<: *default
  database: no_thanks

production:
  <<: *default
  database: no_thanks


